config/routes.rb
Rails.application.routes.draw do
  resources :blog_books
  root "blog_books#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_book.rb
class BlogBook < ApplicationRecord
    validates :title,:author,:ratting,:description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_books_controller.rb
class BlogBooksController < ApplicationController
  before_action :set_blog_book, only: %i[ show edit update destroy ]

  # GET /blog_books or /blog_books.json
  def index
    @blog_books = BlogBook.all
  end

  # GET /blog_books/1 or /blog_books/1.json
  def show
  end

  # GET /blog_books/new
  def new
    @blog_book = BlogBook.new
  end

  # GET /blog_books/1/edit
  def edit
  end

  # POST /blog_books or /blog_books.json
  def create
    @blog_book = BlogBook.new(blog_book_params)

    respond_to do |format|
      if @blog_book.save
        format.html { redirect_to blog_book_url(@blog_book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @blog_book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_books/1 or /blog_books/1.json
  def update
    respond_to do |format|
      if @blog_book.update(blog_book_params)
        format.html { redirect_to blog_book_url(@blog_book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @blog_book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_books/1 or /blog_books/1.json
  def destroy
    @blog_book.destroy!

    respond_to do |format|
      format.html { redirect_to blog_books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_book
      @blog_book = BlogBook.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_book_params
      params.require(:blog_book).permit(:title, :author, :ratting, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_books_helper.rb
module BlogBooksHelper
end

app/views/blog_books/_blog_book.html.erb
<div id="<%= dom_id blog_book %>">
  <p>
    <strong>Title:</strong>
    <%= blog_book.title %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= blog_book.author %>
  </p>

  <p>
    <strong>Ratting:</strong>
    <%= blog_book.ratting %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= blog_book.description %>
  </p>

</div>

app/views/blog_books/_form.html.erb
<%= form_with(model: blog_book) do |form| %>
  <% if blog_book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blog_book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% blog_book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :ratting, style: "display: block" %>
    <%= form.text_field :ratting %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit "Create Book" %>
  </div>
<% end %>

app/views/blog_books/edit.html.erb
<h1>Editing blog book</h1>

<%= render "form", blog_book: @blog_book %>

<br>

<div>
  <%= link_to "Show this book", @blog_book %> |
  <%= link_to "Back to books", blog_books_path %>
</div>

app/views/blog_books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Blog Livors Que Li</h1>

<div id="blog_books">
  <% @blog_books.each do |blog_book| %>
    <%= render blog_book %>
    <p>
      <%= link_to "Show this book", blog_book %>
    </p>
  <% end %>
</div>

<%= link_to "Novo Livro", new_blog_book_path %>

app/views/blog_books/new.html.erb
<h1>New blog book</h1>

<%= render "form", blog_book: @blog_book %>

<br>

<div>
  <%= link_to "Back to books", blog_books_path %>
</div>

app/views/blog_books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @blog_book %>

<div>
  <%= link_to "Edit this book", edit_blog_book_path(@blog_book) %> |
  <%= link_to "Back to books", blog_books_path %>

  <%= button_to "Destroy this blog book", @blog_book, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DioRailsBookProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>